---
- name: Converge
  hosts: all
  roles:
    - role: caddy_ansible.caddy_ansible
  tasks:
    - name: Ensure ss is installed (for testinfra)
      ansible.builtin.package:
        name: "iproute{{ '2' if ansible_os_family == 'Debian' }}"
        state: present
